5 1 require login
thinknetica-django-lab-01/Atmostone pull request #46
Opened 2021-02-04 10:00 UTC by Atmostone

Closes #38

2021-02-04 19:48 UTC, morgangt requested changes
pull-request хороший, есть несколько моментов которые стоит доработать, в основном связанны с аккуратностью и документацией

2021-02-04 19:48 UTC, morgangt commented on HotelBook/apps/accounts/views.py
> +    return HttpResponse(html)
предлагаю сразу сделать классом

2021-02-04 19:48 UTC, morgangt commented on HotelBook/apps/main/views.py
>      return render(request, 'main/index.html', context)
Здесь для единообразия давайте тоже сделаем класс 
и в нем просто переопределим метод get_ context

2021-02-04 19:48 UTC, morgangt commented on HotelBook/apps/main/views.py
> +    model = Hotel
Давайте добавим здесь хоть какой нибудь комментарий или лучше docstring

2021-02-08 09:49 UTC, Atmostone commented on HotelBook/apps/accounts/views.py
> +    return HttpResponse(html)
Все исправления добавлю в следующем реквесте чтобы не было конфликтов

2021-02-08 09:50 UTC, merged